
services:
  postgres:
    image: postgres:17.3
    container_name: ${COMPOSE_PROJECT_NAME}_${ENV}_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_CONFIG_FILE: ${POSTGRES_CONFIG}
    volumes:
      - jt-postgres:/var/lib/postgresql/data
    networks:
      - jt-network

  mongo:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}_${ENV}_mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - jt-mongo:/data/db
    networks:
      - jt-network

  redis:
    image: redis:7.4-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_${ENV}_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - jt-redis:/data
    networks:
      - jt-network

  back:
    build: ./backend
    container_name: ${COMPOSE_PROJECT_NAME}_${ENV}_backend
    restart: unless-stopped
    command: npm run start
    ports:
      - "4000:3000"
      - "4100:3000"
    environment:
      NODE_ENV: ${ENV}
      DEBUG: ${DEBUG}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB}
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB}
      REDIS_HOST: redis
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_ROOT_URL: ${EMAIL_ROOT_URL}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - jt-media:/app/media
    depends_on:
      - postgres
      - redis
      - mongo
    networks:
      - jt-network

  front:
    build: ./frontend
    container_name: ${COMPOSE_PROJECT_NAME}_${ENV}_frontend
    restart: unless-stopped
    command: ng serve core --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: ${ENV}
    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - back
    networks:
      - jt-network

  mailpit:
    image: axllent/mailpit
    container_name: ${COMPOSE_PROJECT_NAME}_${ENV}_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP server
      - "4300:8025"  # Web UI: http://127.0.0.1:8025
    networks:
      - jt-network

volumes:
  jt-postgres:
  jt-mongo:
  jt-redis:
  jt-media:

networks:
  jt-network:
    name: jt-network